<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Creneaux;

/**
 * CreneauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreneauxRepository extends \Doctrine\ORM\EntityRepository
{
public function howManySp()
{
  $connection = $this->getEntityManager()->getConnection();
  $sql = `SELECT COUNT(*) FROM fos_user WHERE fos_user.atCount = 1 `;
  $stm = $connection->query($sql);
  $number = $stm->fetch();
  return $number;
}

}
