<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Creneaux;

/**
 * CreneauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreneauxRepository extends \Doctrine\ORM\EntityRepository
{

}
