<?php

namespace AppBundle\Repository;

/**
 * TypeCreneauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCreneauxRepository extends \Doctrine\ORM\EntityRepository
{
}
